config/routes.rb
Rails.application.routes.draw do

  get 'password_resets/new'
  get 'password_resets/edit'

  get 'sessions/new'

  get 'users/new'

  root             'static_pages#home'

  get 'support' => 'static_pages#support'
  get 'about'   => 'static_pages#about'
  get 'contact' => 'static_pages#contact'
  get 'signup'  => 'users#new'

  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'

  get 'deposit' => 'transactions#deposit'
  get 'withdraw' => 'transactions#withdraw'

  resources :users do
    member do
      get :following, :followers
    end
  end

  resources :charges
  resources :transactions
  
  resources :account_activations, only: [:edit]

  resources :password_resets, only: [:new, :create, :edit, :update]

  resources :microposts,    only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]

end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
	before_action :logged_in_user
	
  def deposit
  	@new_transaction = Transaction.new
  end


  def withdraw
  end

  def create
  	form_params = transaction_params
  	puts form_params[:amount]
  	form_params[:amount] = Monetize.parse(form_params[:amount]).fractional
  	puts form_params[:amount]
  	form_params[:user_id] = current_user[:id]
    @new_transaction = Transaction.new(form_params)
    
    amount_human_readable = Money.new(form_params[:amount], 'USD').format

    ap @new_transaction.amount
    ap amount_human_readable

    if @new_transaction.save
      # Indicate to user that they must activate their account through their
      # email before they may proceed.
      flash[:info] = "You just deposited #{amount_human_readable}!"
      redirect_to root_url
    else
    	@new_transaction.amount = amount_human_readable
	    render 'deposit'
    end
  end


  private  # ------------------------------------------------------------

    def transaction_params
      params.require(:transaction).permit(:description, 
      																		:amount, 
      																		:user_id)
    end


end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/views/transactions/_deposit.html.slim
= form_for @new_transaction do |f|
	.col-1.grey New Deposit

	= render 'shared/error_messages', object: f.object

	.col-1
		= f.label :amount
		= f.text_field :amount, 
		    data: { autonumeric: {aSign: '$ ', mDec: 2} }

	.col-1
		= f.label :description, "Description (optional)"
		= f.text_field :description
		
	.col-1.grey
	  = f.submit 'Make deposit', class: 'btn primary'

app/views/transactions/_transaction.html.slim
li id="#{transaction.id}" 
  span.content
    | #{number_to_currency(transaction.amount)}
    p #{transaction.description}
  span.timestamp
    | #{time_ago_in_words(transaction.created_at)} ago 
    - if current_user?(transaction.user)
      = link_to "delete", transaction, method: :delete, data: { confirm: "You sure?" }
      = link_to "edit", edit_transaction_path

app/views/transactions/deposit.html.slim
- provide(:title, 'Make a deposit')

= render 'deposit'

app/views/transactions/withdraw.html.slim
h1 Make a withdrawal!

p Find me in app/views/transactions/withdraw.html.slim