config/routes.rb
Rails.application.routes.draw do

  get 'password_resets/new'
  get 'password_resets/edit'

  get 'sessions/new'

  get 'users/new'

  root             'static_pages#home'

  get 'support' => 'static_pages#support'
  get 'about'   => 'static_pages#about'
  get 'contact' => 'static_pages#contact'
  get 'signup'  => 'users#new'

  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'

  get 'deposit' => 'transactions#deposit'
  get 'withdraw' => 'transactions#withdraw'

  resources :users do
    member do
      get :following, :followers
    end
  end

  resources :charges
  resources :transactions
  
  resources :account_activations, only: [:edit]

  resources :password_resets, only: [:new, :create, :edit, :update]

  resources :microposts,    only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]

end

app/views/layouts/_footer.html.slim
footer.footer
  small
    | Copyright 2015
  nav
    ul
      li= link_to "About", about_path
      li= link_to "Support", support_path
      li= link_to "Contact", contact_path

app/views/layouts/_header.html.slim
body
  header.navbar.navbar-fixed-top.container-fluid.white-bkgd
    
    .navbar-header  
      / Dropdown list toggle (for mobile / small screens)
      button.navbar-toggle.collapsed(
        data-target="#bs-example-navbar-collapse-1" 
        data-toggle="collapse" 
        type="button") +
      a#logo(href=root_path)  Evergreen
    
    / Nav links, forms, and other content for toggling
    #bs-example-navbar-collapse-1.collapse.navbar-collapse
      ul.nav.navbar-nav.navbar-right
        li= link_to 'About', about_path
        - if logged_in?
          li= link_to 'Deposit', deposit_path
          li.dropdown
            a.dropdown-toggle data-toggle="dropdown" href="#" 
              | Account 
              b.caret
            ul.dropdown-menu
              li= link_to "Profile", current_user
              li= link_to "Settings", edit_user_path(current_user)
              li.divider
              li= link_to "Log out", logout_path, method: "delete"
        - else
          li= link_to "Sign up", signup_path
          li= link_to "Log in", login_path

app/views/layouts/_shim.html.slim
/![if lt IE 9]
  | <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js"
  | </script

app/views/layouts/application.html.slim
doctype html
html
  = yield :header_img
  head
    meta content=("text/html; charset=UTF-8") http-equiv="Content-Type" /
    title= full_title(yield(:title))
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    / = javascript_include_tag :defaults



    / <script src="/assets/jquery.js" type="text/javascript"></script>
    / <script src="/assets/jquery_ujs.js" type="text/javascript"></script>

    = csrf_meta_tags
    = render 'layouts/shim'
  body
    = render 'layouts/header'
    .container
      - flash.each do |message_type, message|
        div class=("alert alert-#{message_type}") = message
    = yield
    = render 'layouts/footer'
    = debug(params) if Rails.env.development?